services:
  app:
    build: .
    image: kiar-app
    container_name: kyara-web
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=kiar_secret
      - DB_NAME=kiar
      - PORT=8080
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres

  cron:
    build: .
    image: kiar-cron
    container_name: kyara-cron
    restart: unless-stopped
    command: /bin/sh -c "echo '🚀 Cron worker started' && while true; do node migration/migrate_mudik.js; echo '💤 Sleeping for 15 minutes...'; sleep 900; done"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=kiar_secret
      - DB_NAME=kiar
      - DB_PORT=5432
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: kyara-db
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kiar_secret
      - POSTGRES_DB=kiar
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
