services:
  app:
    build: .
    image: mudik-app
    container_name: mudik-web
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=kiar_secret
      - DB_NAME=kiar
      - PORT=8080
      - ADMIN_API_KEY=kiar-admin-2026-secret
      - RATE_LIMIT_MAX=300
      - GOOGLE_CLIENT_ID=262804834085-jlrslmph5ghovf6ufq796gre8uuoq1ci.apps.googleusercontent.com
      - ALLOWED_EMAILS=sakitmas010@gmail.com,anatasyadea32@gmail.com,tropicans@gmail.com
      - ADMIN_EMAILS=tropicans@gmail.com
      - SUPERADMIN_EMAIL=tropicans@gmail.com
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: mudik-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kiar_secret
      - POSTGRES_DB=kiar
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
